version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgres/data

  web:
    build:
    container_name: "differ"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_POST: "5432"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
